version: '3.7'
services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - ./schemas:/var/lib/mysql:rw
    networks:
      loaclhost:
        aliases:
          - mysql_localhost

volumes:
  schemas: {}

networks:
  loaclhost:
    name: mysql_net
    driver: bridge
